### ISSUE TITLE
is anything wrong in my setup

### ISSUE THREAD

**Issue by zhihuiFan** [rougier/mu4e-thread#1]
Currently my header view looks like this:

![image](https://github.com/rougier/mu4e-thread/assets/3489747/0f112509-0332-487a-8615-ab201439f0e9)

What I really want it to be is  only show the thread-subject once.  which means  show `A recent message added to pg_upgade ` only once. 

I'm not sure if mu4e-thread is designed for this.  I tried `mu4e-thread-fold-apply-all`, looks nothing happens,  including no error at all.    do you have any suggestion on this?  and I'm pretty sorry mu4e-thread has nothing with my requirement.

**Comment by zhihuiFan** [comment]
Here is my non-default setup:

(setq mu4e-headers-fields
      '((:human-date . 12)
        (:flags . 6)
        (:mailing-list . 10)
        (:from . 22)
        (:thread-subject  . 75)))

mu --version
version 1.10.7

**Comment by rougier** [comment]
This is two separate problems. Folding should work if mails are read or if `mu4e-thread-fold-unread` has been set to `t`.

To not repeat the header line, you'll need to provide your own thread-subject function and return "" when the message is not the root of the thread (have a look [here](https://github.com/rougier/mu4e-thread/blob/master/mu4e-thread.el#L100) to knwo if a message is root or not)

**Comment by zhihuiFan** [comment]
Thanks you @rougier  for the reply,  I have got used to the current situation:)   So just closed this issue.
